Add ui
NYUDevOpsInventory/inventory pull request #93
Opened 2018-04-25 01:57 UTC by MingshiPeng

How to run:
1. `vagrant up && vagant ssh`
1. `cd /vagrant`
1. `python run.py`
1.  Open a browser and access `localhost:5000`

UI Screenshot:
<img width="1081" alt="screen shot 2018-04-24 at 9 51 49 pm" src="https://user-images.githubusercontent.com/19756129/39222333-305e29ac-480a-11e8-8a2e-aad9127e5f14.png">

2018-04-25 15:28 UTC, nideyidayida requested changes

2018-04-25 15:28 UTC, jockyxu1122 commented on app/server.py
> +    return app.send_static_file('index.html')
Does this file contain the link to Swagger docs?

2018-04-25 15:28 UTC, jockyxu1122 commented on app/static/js/rest_api.js
> +            //alert(res.toSource())
Remove if don't need it

2018-04-25 15:28 UTC, jockyxu1122 commented on app/static/js/rest_api.js
> +            //alert(res.toSource())
remove

2018-04-25 15:36 UTC, majia67 approved these changes
LGTM. Please see the comments for nit problems.

2018-04-25 15:36 UTC, majia67 commented on app/static/index.html
> +</html>
new line

2018-04-25 17:25 UTC, nideyidayida approved these changes
good

2018-04-25 17:26 UTC, merged

2018-04-25 17:29 UTC, majia67 commented
IBM Cloud [toolchain](https://console.ng.bluemix.net/devops/toolchains/d4dd8efb-da17-4b0c-b4e6-5599ec73dd60?env_id=ibm%3Ayp%3Aus-south "nyu-inventory-service-s18"): [Delivery Pipeline](https://console.ng.bluemix.net/devops/pipelines/c71be43a-8963-4052-b97c-5da9b99de3f9?env_id=ibm%3Ayp%3Aus-south "nyu-inventory-service-s18") deployed [inventory](https://github.com/NYUDevOpsInventory/inventory/releases/tag/deploy-ibm-yp-us-south-NYU_Devops_Inventory_Org-dev-20180425-172929 "deploy-ibm-yp-us-south-NYU_Devops_Inventory_Org-dev-20180425-172929") to [dev](https://console.bluemix.net/apps/1db994d8-c4f1-4076-85c0-7ff2674244e5?env_id=ibm:yp:us-south "ibm:yp:us-south:NYU_Devops_Inventory_Org:dev"), including commit 88a06923f5bca90f104e0b390f0e8685514d24b4

2018-05-01 18:36 UTC, majia67 commented
IBM Cloud [toolchain](https://console.ng.bluemix.net/devops/toolchains/d4dd8efb-da17-4b0c-b4e6-5599ec73dd60?env_id=ibm%3Ayp%3Aus-south "nyu-inventory-service-s18"): [Delivery Pipeline](https://console.ng.bluemix.net/devops/pipelines/c71be43a-8963-4052-b97c-5da9b99de3f9?env_id=ibm%3Ayp%3Aus-south "nyu-inventory-service-s18") deployed [inventory](https://github.com/NYUDevOpsInventory/inventory/releases/tag/deploy-ibm-yp-us-south-NYU_Devops_Inventory_Org-prod-20180501-183630 "deploy-ibm-yp-us-south-NYU_Devops_Inventory_Org-prod-20180501-183630") to [prod](https://console.bluemix.net/apps/e25e653b-a50f-4831-b93e-d8f9f484a484?env_id=ibm:yp:us-south "ibm:yp:us-south:NYU_Devops_Inventory_Org:prod"), including commit 88a06923f5bca90f104e0b390f0e8685514d24b4